name: docker-publish

on:
  workflow_dispatch:

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get artifacts
        run: |
          bash get_artifacts.sh ${{ secrets.GITHUB_TOKEN }} v4.15.0
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Fork from https://github.com/koishijs/boilerplate/blob/master/.github/workflows/docker.yml
      - name: Run buildx and push
        env:
          DOCKER_REPO: swr.cn-south-1.myhuaweicloud.com/container-repositories/napcat-docker
          GITHUB_REPO: NapNeko/NapCatQQ
        run: |
          TAG=v4.15.0
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --tag ${DOCKER_REPO}:$TAG \
            --tag ${DOCKER_REPO}:latest \
            --file ./Dockerfile \
            --provenance=false \
            --sbom=false \
            .
      - name: Docker Hub logout
        if: always()
        run: docker logout
